### ISSUE TITLE
compile error only in release mod?

### ISSUE THREAD

**Issue by flankechen** [edrosten/libcvd#11]
HI all, I am trying to build libcvd and after a few try, I success in debug mod but the release mod always complains like:

1>  Performing Custom Build Tools
1>  系统找不到指定的文件。
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.CppCommon.targets(172,5): error MSB6006: "cmd.exe" exited with code 1.

I am upgrading the project from vs2008 to vs2012 on win7 x64.
it's wired that I am able to build things in debug mod. getting libcvdd.lib.
any idea about this?

**Comment by flankechen** [comment]
I figure it out!
this is because of custom build things. 
open .vcxproj file and search for <custombuild> tag. and carefully check things inside. the difference between debug and release cause this problem. 

    <CustomBuild Include="config.h">
      <Command Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">copy ..\vc2005\%(Filename)%(Extension) ..\..\cvd\</Command>
      <Command Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">copy ..\vc2005\%(Filename)%(Extension) ..\..\cvd\</Command>
      <Outputs Condition="'$(Configuration)|$(Platform)'=='Debug|Win32'">..\..\cvd\%(Filename)%(Extension);%(Outputs)</Outputs>
      <Outputs Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">..\..\cvd\%(Filename)%(Extension);%(Outputs)</Outputs>
      <Command Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">copy ..\vc2005\%(Filename)%(Extension) ..\..\cvd\</Command>
      <Command Condition="'$(Configuration)|$(Platform)'=='Release|x64'">copy %(Filename)%(Extension) ..\..\cvd\</Command>
      <Outputs Condition="'$(Configuration)|$(Platform)'=='Release|Win32'">..\..\cvd\%(Filename)%(Extension);%(Outputs)</Outputs>
      <Outputs Condition="'$(Configuration)|$(Platform)'=='Release|x64'">..\..\cvd\%(Filename)%(Extension);%(Outputs)</Outputs>
    </CustomBuild>

**Comment by edrosten** [comment]
Thanks for the report. I'm glad you got it fixed.

-Ed
