### ISSUE TITLE
impossible to compile ".deps" error

### ISSUE THREAD

**Issue by giancan** [edrosten/libcvd#14]
Dear all,
I have a working linux ubuntu 14.04 and I am trying to compile libcvd (which I need for a camera calibration with ptam).
I used the config make make install sequence but I keep on getting

`.deps:1:*** missing separator. Stop.
`
I checked that I have all the required programs and it seems I have.
I really don't know what else to check.
Can anybody help me with this?

Thanks,
Gianluca

**Comment by edrosten** [comment]
Hi,

Can you try deleting .deps and typing make? Let me know what that does.

sent from phone.

**Comment by giancan** [comment]
If I delete and make I get this
```
(after many generate_dependencies.bash: line 5: -I.: command not found) 
make: *** [.deps] Error 127
```

**Comment by edrosten** [comment]
Can you attach the output of configure, the config.log file, and the
generated makefile

sent from phone.

**Comment by giancan** [comment]
Here you go! Thanks

[config.log.txt](https://github.com/edrosten/libcvd/files/187751/config.log.txt)

[Uploading Makefile.txt…]()

**Comment by giancan** [comment]
[Makefile.txt](https://github.com/edrosten/libcvd/files/189412/Makefile.txt)

**Comment by giancan** [comment]
@edrosten Are the file I uploaded of any use to understand what's the problem?
Is there anything I can do to fix it and get it running?
Thanks,
G

**Comment by edrosten** [comment]
Hi,

I've come down with some bug (not just libcvd) so it's going to take me a
few a days to get to this.

sent from phone.

**Comment by edrosten** [comment]
Getting back to it: this is very strange, I don't know how it ever worked. I've pushed a fix on master. Let me know if it works for you, or if you need it fixed on a branch.

Thanks for the bug report.

**Comment by giancan** [comment]
Hi @edrosten 
thanks for taking care of it.
Unfortunately now I have a new error after "make"

make: *** [cvd_src/diskbuffer2.o] Error 1

Let me know if there is anything I can do to provide you with further information.
Thanks

**Comment by edrosten** [comment]
Is that the entirety of the error message?

-Ed

**Comment by giancan** [comment]
Yes, as far as my understanding goes...
If needed I can upload log files or whatever other file you may need to check

**Comment by edrosten** [comment]
Huh, that's very unusual. Normally there'll be some indication the few
lines before of what's gone wrong. Can you do:

make clean
rm .deps

{ ./configure && make ; } > log.txt 2>&1

and send me log.txt
