### ISSUE TITLE
cvd_src/diskbuffer2.o Error 1

### ISSUE THREAD

**Issue by giancan** [edrosten/libcvd#15]
Hi @edrosten  
thanks for taking care of the other problem  https://github.com/edrosten/libcvd/issues/14
Unfortunately now I have a new error after "make"

make: *** [cvd_src/diskbuffer2.o] Error 1

Let me know if there is anything I can do to provide you with further information.
Thanks

**Comment by giancan** [comment]
[log.txt](https://github.com/edrosten/libcvd/files/199884/log.txt)

**Comment by edrosten** [comment]
That's strange, gcc seems to be missing is_trivially_copyable.

Which compiler version are you using?

-Ed

**Comment by giancan** [comment]
I have gcc 4:4.8.2-1

**Comment by giancan** [comment]
Just for your information, I just repeated the process on a freshly installed vbox machine and I got the same error about is_trivially_copyable

**Comment by edrosten** [comment]
Interesting...

This might be a gcc bug. Can you try installing gcc 5 from the PPA and
compiling with that instead?

sent from phone.

**Comment by giancan** [comment]
Hi, I just installed the gcc5 and run again configure and make but I got the same error (unless I had to pass some parameters to make which I didn't).

**Comment by giancan** [comment]
[log_gcc5.txt](https://github.com/edrosten/libcvd/files/202263/log_gcc5.txt)

This is the new log after gcc update

**Comment by giancan** [comment]
And here is the gcc version

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.3.0-3ubuntu1~14.04' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=gcc4-compatible --disable-libstdcxx-dual-abi --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.3.0 20151204 (Ubuntu 5.3.0-3ubuntu1~14.04)

**Comment by edrosten** [comment]
Looks like it's still picking up the system gcc.

try:

export CXX=g++-5
export LD=g++-5
make clean
./configure && make

Alternatively edit the Makefile and change g++ to g++-5

**Comment by giancan** [comment]
After I did what you suggest, I got into a different error.
Here is the log file.

[log_after_export.txt](https://github.com/edrosten/libcvd/files/202690/log_after_export.txt)

Thanks for your patience,
Gianluca

**Comment by edrosten** [comment]
Looks like a missing file. I've just pushed a fix. Can you try it?

-Ed

**Comment by giancan** [comment]
now it's this

make: *** [cvd_src/i686/convolve_gaussian.o] Error 1

**Comment by edrosten** [comment]
Can you send the complete log as before?

-Ed

**Comment by giancan** [comment]
Sure
[log_after_export2.txt](https://github.com/edrosten/libcvd/files/202754/log_after_export2.txt)

**Comment by edrosten** [comment]
Thanks, I;ll take a look.

-Ed

**Comment by giancan** [comment]
Hi  @edrosten  , any news on the issue?

**Comment by edrosten** [comment]
Try the latest commits as of about now.

Thanks for trying out the beta version of libCVD!

-Ed

**Comment by giancan** [comment]
Thanks @edrosten .
It worked fine on the virtual machine, but on the other machine I got an error on make

No rule to make target cvd/abs.h, needed by 'cvd_src/convolution.o'
Do you prefer to see the new log?

**Comment by edrosten** [comment]
This is all very strange. I'm going to have to check what's going on on the
continuous integration server!

Try the latest commit.

-Ed

**Comment by giancan** [comment]
Super! now it seems that we managed. Of course now I have new problems (compiling ptam) but they have not to do with your software (from what i can understand).
Thanks a lot!!!

**Comment by edrosten** [comment]
On 6 April 2016 at 15:59, Gianluca <notifications@github.com> wrote:

> Super! now it seems that we managed. Of course now I have new problems
> (compiling ptam) but they have not to do with your software (from what i
> can understand).
> Thanks a lot!!!
>
Ah Ptam may be a bit difficult with this version of CVD. I've tried to
avoid breaking compatibility but it may  not be 100%.  You might want to
try out the stable branch of libCVD.

-Ed

**Comment by DxsGeorge** [comment]
I seem to have the same issue, build stops at convolution.o . I am attaching the logfile.

[log_apr16_commit.txt](https://github.com/edrosten/libcvd/files/1010502/log_apr16_commit.txt)
