### ISSUE TITLE
Which is the current stable release for c++11?

### ISSUE THREAD

**Issue by bpwiselybabu** [edrosten/libcvd#16]
I tried compiling the c++11 branch but it seems to not compile. What is the current stable release for non C++14 compilers?

**Comment by bpwiselybabu** [comment]
My build fails with

> make: *** No rule to make target `cvd/internal/concurrency_utilities.h', needed by `cvd_src/videosource.o'.  Stop.

**Comment by edrosten** [comment]
Sounds like a bug. I'll look into it!

sent from phone.

**Comment by edrosten** [comment]
Hi, the libcvd 1.x branch is still occasionally getting updates for compatibility. That should work.

That said, the master branch while not 100% stable should be in a functional state.
