### ISSUE TITLE
thread.h and utility.h

### ISSUE THREAD

**Issue by HDaoud** [edrosten/libcvd#20]
Dear Edward,

I would like to report two issues with the latest commit, although it worked previously, however, it was due to the usage of old files, when recompiling `PTAMM` two errors in two files are arising,

First one is in `utility.h`, which I reported earlier, the usage of `convert_image(...)` this line was added to fix the `totallength(..)`, however, it requires to add `#include<cvd/image_conver.h>`.

The second issue is when compiling PTAMM, the following error is thrown:
`undefined reference to`CVD::Thread::isRunning() const'`

I tried to use the old thread.cpp file, but many errors of "redefinition" was shown, I reconfigured libcvd and make, make install, but still showing the error.

Thanks!

**Comment by HDaoud** [comment]
Forgot to mention that I added -lpthread to Makefile. but still showing this error (before adding it, other errors where shown about threading).

**Comment by HDaoud** [comment]
Hello Dear Edward,

I have found the issue to be that in `thread.h` there is no implementation for `bool isRunning()` therefore I added the following:

>//! Returns true if the thread is still running.
			bool isRunning() const
			{
				return myRunningFlag;
			}

and no more `undefined reference` errors.

Hope you could solve these two issues and push them to master.

Thank you!

**Comment by edrosten** [comment]
Looks like the method definition never got pasted back in. Since
CVD::thread is now a trivial (and buggy!) wrapper around std::thread, I've
moved everything inline so there's no corresponding source file.

Can you test it?

-Ed

**Comment by edrosten** [comment]
First one is in utility.h, which I reported earlier, the usage of
> convert_image(...) this line was added to fix the totallength(..),
> however, it requires to add #include<cvd/image_conver.h>.
>

Sorry, there's been so much back and fort that I've got a bit lost. Can you
restate the problem?

-Ed

**Comment by HDaoud** [comment]
Hi Edward,

I've reference the commit where the first error is happening, it's just a missing library.

for the fix for `thread.h` it's working fine.

Feel free to close this issue once `#include<cvd/image_convert.h>` is added to `utility.h` 

Thank you for your patience and hard-work.
