### ISSUE TITLE
doesn't compile on mac os sierra

### ISSUE THREAD

**Issue by atv2016** [edrosten/libcvd#23]
./cvd/internal/scalar_convert.h:112:4: error: unknown type name 'constexpr'
                        constexpr static trivial_array<float, 512> float_for_byte = buildLookupTable<float>();
                        ^
./cvd/internal/scalar_convert.h:112:14: error: expected unqualified-id
                        constexpr static trivial_array<float, 512> float_for_byte = buildLookupTable<float>();
                                  ^
./cvd/internal/scalar_convert.h:113:4: error: unknown type name 'constexpr'
                        constexpr static trivial_array<double, 512> double_for_byte = buildLookupTable<double>();
                        ^
./cvd/internal/scalar_convert.h:113:14: error: expected unqualified-id
                        constexpr static trivial_array<double, 512> double_for_byte = buildLookupTable<double>();
                                  ^
./cvd/internal/scalar_convert.h:117:56: error: no member named 'float_for_byte' in namespace
      'CVD::Pixel::Internal::Internal'
                inline float byte_to_float(int b) { return Internal::float_for_byte[b+255]; }
                                                           ~~~~~~~~~~^
./cvd/internal/scalar_convert.h:118:58: error: no member named 'double_for_byte' in namespace
      'CVD::Pixel::Internal::Internal'
                inline double byte_to_double(int b) { return Internal::double_for_byte[b+255]; }
                                                             ~~~~~~~~~~^
In file included from cvd_src/diskbuffer2.cc:3:
In file included from ./cvd/diskbuffer2.h:12:
In file included from ./cvd/image_io.h:7:
In file included from ./cvd/image_convert.h:5:
In file included from ./cvd/internal/convert_pixel_types.h:9:
In file included from ./cvd/internal/rgb_components.h:4:
./cvd/rgb.h:28:11: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
  Rgb() = default;
          ^
./cvd/rgb.h:29:21: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
  Rgb(const Rgb&) = default;
                    ^
./cvd/rgb.h:30:30: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
  Rgb& operator=(const Rgb&)=default;
                             ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
16 warnings and 20 errors generated.
make: *** [cvd_src/diskbuffer2.o] Error 1

etc

**Comment by edrosten** [comment]
Looks like you've got an old C++ compiler or C++11/14 support is not
enabled.

Can you send me the full output of autoconf?

**Comment by atv2016** [comment]
send it to you on email, did you manage to have a look please.
thanks a lot.

**Comment by edrosten** [comment]
Yep, I'm pretty sure the compiler is too old (but accpts the -std=c++1y flag!). Which version are you using?
