### ISSUE TITLE
Trouble compiling on macOS Sierra

### ISSUE THREAD

**Issue by LukeGarnsey** [edrosten/libcvd#24]
I've been having all sorts of issues trying to build on sierra.  

Software I have:
- XCode Version 8.2.1 (8C1002)
  - included gcc/g++: 
    - > Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

I have also attempted with the version of gcc on homebrew, which is gcc 6.3.0.

Anyways, when I just ./configure && make, I get a bunch of errors, some cherry picked:

```
./cvd/image.h:234:19: error: cannot template a using declaration
template<class C> using SubImage [[deprecated]]= BasicImage<C>;
~~~~~~~~~~~~~~~~~~^
./cvd/image.h:264:34: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
                        ImageData(const ImageData&) = default;

./cvd/internal/scalar_convert.h:91:5: error: unknown type name 'constexpr'
                                constexpr T& operator[](size_t i)
```
and much more.

However, if do: `./configure CXXFLAGS="-std=c++14"`, to force c++14 support, I am able to get past that.  However, I get a new error:

```
make: *** No rule to make target `jpeglib.h', needed by `cvd_src/image_io/jpeg.o'.  Stop.
```

Which makes sense, except I _DO_ have jpeglib installed (using homebrew).  Based on what I know, and based on what I'm seeing in the generated Makefile, it should properly link against the library.

I am a bit foreign to C++ development; it's been 5 or 6 years since I've dipped my toes into it, so maybe there's something obvious that i'm missing?

Thanks!

**Comment by edrosten** [comment]
Hm there seems to be something wrong with the C++14 detection. Guess I better fix that!

With respect to the jpeglib thing, it looks like the .deps file has got stale. Can you delete .deps and try again?

**Comment by edrosten** [comment]
Should be fixed now (works on my mac)
