### ISSUE TITLE
Which sln should i use  on visual studio ?

### ISSUE THREAD

**Issue by alvaro562003** [edrosten/libcvd#25]
Hello,
I am trying to install fivepoint from Lui and Drummond (https://bitbucket.org/whvlui/fivepoint).
The prerequisite is libcvd ( ,TaG &  GVars3) 

I am using microsoft visual studio 2015.

Should i use libcvd.sln or libcvd-TooN.sln ?

**Comment by edrosten** [comment]
On 20 January 2017 at 11:33, alvaro562003 <notifications@github.com> wrote:

> Hello,
> I am trying to install fivepoint from Lui and Drummond (
> https://bitbucket.org/whvlui/fivepoint).
> The prerequisite is libcvd ( ,TaG & GVars3)
>
> I am using microsoft visual studio 2015.
>
Should i use libcvd.sln or libcvd-TooN.sln ?
>
That depends on whether you want libCVD compiled with TooN support. Unless
you're on an old branch of libCVD though, those are very unlikely to work.
There are however very many fewer platform dependencies than there used to
be so making a new build file shouldn't be too hard.

-Ed
