### ISSUE TITLE
Compiling error in Ubuntu 14.04 with gcc-6

### ISSUE THREAD

**Issue by kerolex** [edrosten/libcvd#28]
Hi @edrosten 
I am trying to compile libcvd Release 07/04/2015 on Ubuntu 14.04 with GCC 6.2.0. However, the compiler returns many errors related to an ambiguity with array.

Please see the file below for details.
[log.txt](https://github.com/edrosten/libcvd/files/812291/log.txt)

I hope you can give me an advice about it.
Thank you in advance.

**Comment by edrosten** [comment]
Definitely looks like a bug.

Can you try pulling the latest version on the CVD-1.x branch (not the
master branch) from git? I believe the bug is fixed there.

-Ed

**Comment by kerolex** [comment]
Thank you @edrosten for your reply. 
However, even after trying the latest version on the CVD-1.x branch, the issue did not change. 
I will let you know If I can solve it.

**Comment by edrosten** [comment]
Should all be working now (tested on 16.06 with gcc 6.3.0).
