### ISSUE TITLE
missing config.h file in installation of libcvd

### ISSUE THREAD

**Issue by shubhraD** [edrosten/libcvd#29]
All the references to config.h file were removed and hence while configuring it,i didnt face any issue,
but the while running make cmd, it gave me this error:
 cvd/config.h: No such file or directory
compilation terminated.
Kindly reply with solution or reference of config.h file asap,i am not able to resolve it.

ref: I needed the dependencies of TooN, libcvd  for ethzasl_ptam   but the compilation of libcvd is not completed.

**Comment by edrosten** [comment]
Hi,

yes that's correct. The head of the master branch is currently undergoing a
bit of a rewrite to modernise it and it's in a broken state for the moment.
Can you drop back to an older point?

-Ed

**Comment by shubhraD** [comment]
*** No rule to make target 'cvd/config.h', needed by 'cvd_src/image_io/bmp_read.o'.  Stop.

I assume that config.h file was supposed to be auto generated. but it isn't. 
Has anyone faced this problem earlier or have i missed something?











@

**Comment by edrosten** [comment]
On 10 March 2017 at 11:22, shubhraD <notifications@github.com> wrote:

> *** No rule to make target 'cvd/config.h', needed by
> 'cvd_src/image_io/bmp_read.o'. Stop.
>
> I assume that config.h file was supposed to be auto generated. but it
> isn't.
> Has anyone faced this problem earlier or have i missed something?
>
It's temporarily broken. I'm in the middle of removing as much of the
config file as I can, since it's a bad design. Can you revert to an older
version until it's fixed?


-Ed

**Comment by edrosten** [comment]
I've reverted the change and put it on a branch. The mastre branch is now
safe to use.

**Comment by shubhraD** [comment]
marry me . It worked.
