### ISSUE TITLE
Compiling error with x64 Platform in VS2015

### ISSUE THREAD

**Issue by hobinson** [edrosten/libcvd#31]
It's OK to compile with Win32 Platform in VS2015, but failed after switching to x64 platform. The errors are as below:
-------------------------------------------------------------------------------------------------------------
1>  gradient.cc
1>..\..\cvd_src\i686\gradient.cc(66): error C3861: “_mm_empty”: Identifier not found
1>  utility_byte_differences.cc
1>..\..\cvd_src\i686\utility_byte_differences.cc(9): error C3861: “_mm_setzero_si64”: Identifier not found
1>..\..\cvd_src\i686\utility_byte_differences.cc(13): error C3861: “_mm_unpacklo_pi8”: Identifier not found
1>..\..\cvd_src\i686\utility_byte_differences.cc(14): error C3861: “_mm_unpackhi_pi8”: Identifier not found
1>..\..\cvd_src\i686\utility_byte_differences.cc(15): error C3861: “_mm_unpacklo_pi8”: Identifier not found
1>..\..\cvd_src\i686\utility_byte_differences.cc(16): error C3861: “_mm_unpackhi_pi8”: Identifier not found
1>..\..\cvd_src\i686\utility_byte_differences.cc(17): error C3861: “_mm_sub_pi16”: Identifier not found
1>..\..\cvd_src\i686\utility_byte_differences.cc(18): error C3861: “_mm_sub_pi16”: Identifier not found
1>..\..\cvd_src\i686\utility_byte_differences.cc(20): error C3861: “_mm_empty”: Identifier not found
1>..\..\cvd_src\i686\utility_byte_differences.cc(26): error C3861: “_mm_sub_pi16”: Identifier not found
1>..\..\cvd_src\i686\utility_byte_differences.cc(28): error C3861: “_mm_empty”: Identifier not found
--------------------------------------------------------------------------------------------------------------
It seems that MMX intrinsics are not available in visual c++ 64bit compiler.
I found some explanations in https://social.msdn.microsoft.com/Forums/en-US/02887764-ec3e-48c2-ac7f-94700ee763a9/problem-using-mmx-intrinsics-when-compiling-64bit-applications?forum=vcgeneral

**Comment by edrosten** [comment]
Ah building on windows.

I'm afraid the Windows build system hasn't seen much love recently and
probably won't work with a recent version of libCVD. You can try an older
version. Alternatively, the more recent versions (the beta ones) using
C++14 are more portable with rather less effort than before. If you're
interested in porting it, let me know and I can offer assistance.

-Ed
