### ISSUE TITLE
Trouble compiling libCvd on ubuntu 14.04

### ISSUE THREAD

**Issue by YonatanSimson** [edrosten/libcvd#34]
I verified that I have GCC version >5. by:
sudo apt-get install g++-5

I get the following error:

```
./cvd/image.h: In member function ‘void CVD::BasicImage<C>::zero()’:
./cvd/image.h:508:18: error: ‘is_trivially_copyable’ is not a member of ‘std’
    static_assert(std::is_trivially_copyable<T>::value, "Error: zero() only works on POD types");
```

I have included logs both from configure
[configure.txt](https://github.com/edrosten/libcvd/files/1021863/configure.txt)

 and make:
[compile.txt](https://github.com/edrosten/libcvd/files/1021865/compile.txt)

The latest version of TooN was installed prior to this.

**Comment by edrosten** [comment]
gcc-5 appears to be not quite compliant and can't compile libCVD. Can you get g++-6 or -7 instead?
