### ISSUE TITLE
what's the algorithm or formular converting image from RGB to Gray using the CVD method convert_image?

### ISSUE THREAD

**Issue by GaoHongchen** [edrosten/libcvd#36]
i have no idea about the algorithm of convert_image method which is used to convert image from RGB to Gray when I study PTAM project. is it the same as the commom formular Y = 0.299*R + 0.587*G + 0.114*B ? if not, what is the formular?

**Comment by edrosten** [comment]
Yep it's that to a good number of bits of precision. I use the constants:

	  const double wr=0.2989959716796875, wg=0.587005615234375, wb=0.1139984130859375;

which sum to 1, unlike the floating point representations of 0.299 + 0.587 + 0.114

https://github.com/edrosten/libcvd/blob/master/cvd/internal/convert_pixel_types.h#L50-L65
