### ISSUE TITLE
How can I output a dynamic link lib(.so) in Ubuntu16.04?

### ISSUE THREAD

**Issue by BKAUTO** [edrosten/libcvd#51]
for cmake it output a libcvd.a. But my project now need a libcvd.so. Thank you!

**Comment by edrosten** [comment]
I've not done much work on the CMakeLists. The autoconf build will make a .so file.

**Comment by BKAUTO** [comment]
Yeah but I found maybe the autoconf method failed to check the libjpeg and libpng dependence. I've already generated the .so file by setting the CMakeList, thanks.

**Comment by heethesh** [comment]
@BKAUTO how did you generate the .so files?

**Comment by BKAUTO** [comment]
Sorry it's quite a long time and I failed to find the relevant file by now. It is very simple to change the compile target to a .so file(dynamic link) instead of a .a file(static link) in CMake. You may google to find the command and revise it in the CMakeList.txt.

**Comment by heethesh** [comment]
@BKAUTO Thanks for your reply. I managed to compile the dynamic libs.
Had to update the CMake file with this `add_library(${PROJECT_NAME} SHARED ${SRCS} ${HEADERS})`. Furthermore, I had to manually add these flags `-lGL -lGLU -lGLEW -lglut` in `link.txt` files generated in my build cmake files folders for some targets to properly link against OpenGL libraries
