### ISSUE TITLE
Error: ld: library not found for -lstdc++

### ISSUE THREAD

**Issue by skylook** [edrosten/libcvd#9]
Here is what step I was following:
First, run:
./configure_osx_32bit --without-ffmpeg --x-libraries=/usr/X11/lib --x-includes=/usr/X11/include

Second:
make

And I got these errors:

clang: warning: argument unused during compilation: '-pthread'
ld: library not found for -lstdc++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libcvd.dylib] Error 1

How should I fix it?

**Comment by GerrieWell** [comment]
Have you solved it ? 
How to add stdlib?

**Comment by edrosten** [comment]
This sounds like a bug.

Can you send me the output of your configure script as well as config.log?


-Ed
